### ISSUE TITLE
Error:Already connected  javax.ws.rs.ProcessingException: Already connected

### ISSUE THREAD

**Issue by nikned** [SecureAuthCorp/saidp-sdk-java#45]
@rrowcliffe  @thomasleplus @CharlieC3 @elordahl 

We are using websphere 9 as app server . 
Error:Already connected  javax.ws.rs.ProcessingException: Already connected error on making API calls 

**Stack :** 
https://XXXX:443/secureauth1/api/v1/adaptauth
Error:Already connected
                                 javax.ws.rs.ProcessingException: Already connected
at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:236)
at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:655)
at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:652)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:422)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:652)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:412)
at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:321)
at org.secureauth.sarestapi.resources.SAExecuter.executePostRequest(SAExecuter.java:406)
at org.secureauth.sarestapi.SAAccess.adaptiveAuthQuery(SAAccess.java:188) 

Properties set when creating api connection : 
ssl=true
selfSigned=false or selfSigned=true ( both have same issue)

We also added self-signed cert on websphere , dint make any difference .

NOTE : I can make https calls from my local machine without any issue with the following property settings:

ssl=true
selfSigned=true

**Comment by sa-rrowcliffe** [comment]
@nikned TLS might need to be updated in SAExecutor.java to support the TLS version websphere is using.

**Comment by nikned** [comment]
@sa-rrowcliffe  , updating ctx = SSLContext.getInstance("TLS"); to ctx = SSLContext.getInstance("TLSv1.2"); fixed the issue . 

I believe in JAVA 8 TLS is defaulted to “TLSv1.2”, thus app servers which are strict checking on TLS type will break by using TLS instance instead of TLSv1.2.
Probably on secure auth end you can investigate the impact of this on different app servers and include this change accordingly on the SDK appropriately as a bug fix in your next release.

**Comment by glacuesta-sa** [comment]
This will be addressed on RAD-780 next version.
